Module6 add missed pages
artembert/461957-typoteka-3 pull request #2
Opened 2020-12-20 15:08 UTC by artembert

2020-12-21 11:08 UTC, LordotU requested changes

2020-12-21 11:08 UTC, LordotU commented on src/express/routes/articles.router.ts
> +      next(new SSRError({message: `Failed to get article`, statusCode: HttpCode.INTERNAL_SERVER_ERROR}));
В этом и подобных кейсах очень просится ранний `return`, чтобы не плодить ветвлений. Проверили сразу после получения данные на `null` и отстрелили ошибкой, если надо.

2020-12-21 11:08 UTC, LordotU commented on src/service/server/services/data-provider.service.ts
> +        articles.forEach(article => {
Многовато циклов для перелопачивания данных. Может, попробовать сделать как-то элегантнее? Например, постараться сформировать нужную структуру сразу при первом проходе, чтобы потом ниже не мапить

2020-12-21 19:49 UTC, artembert commented on src/express/routes/articles.router.ts
> +      next(new SSRError({message: `Failed to get article`, statusCode: HttpCode.INTERNAL_SERVER_ERROR}));
Исправил

2020-12-21 19:52 UTC, artembert commented on src/service/server/services/data-provider.service.ts
> +        articles.forEach(article => {
Собираюсь уже в следующем шаге отказаться от этого модуля - сейчас он замещает подключение к базе данных.

2020-12-22 18:15 UTC, LordotU approved these changes

2020-12-22 18:18 UTC, merged